name: flutterapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  pie_chart: ^5.4.0
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  flutter_sound: ^9.16.3
  path_provider: ^2.1.4
  http: ^1.2.2
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  audioplayers: ^6.1.0
  flutter_tts: ^3.2.0  # New dependency for text-to-speech
  flutter_local_notifications: ^17.2.4
  socket_io_client: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  audioplayers: ^6.1.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alert.mp3
    - assets/
    - assets/smile.jpg
    - assets/mic.jpg
    - assets/cry_dark.jpg
    - assets/cry.jpg
